# Generated by Django 2.1a1 on 2018-06-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=100)),
                ('new_text', models.TextField()),
                ('news_created_date', models.DateTimeField()),
                ('news_updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='news_imgs',
            fields=[
                ('imgs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('imgs_item', models.ImageField(blank=True, null=True, upload_to='')),
                ('imgs_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
