# Generated by Django 2.1a1 on 2018-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_imgs',
            name='imgs_news',
        ),
        migrations.DeleteModel(
            name='news_imgs',
        ),
    ]
