# Generated by Django 2.1a1 on 2018-06-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180608_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_text',
            new_name='news_text',
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='img_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
