# Generated by Django 2.1a1 on 2018-06-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_num', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=10)),
                ('brand_id', models.CharField(max_length=12)),
                ('brand_pw', models.CharField(max_length=15)),
                ('brand_address', models.CharField(max_length=60)),
                ('brand_email', models.CharField(max_length=30)),
                ('brand_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_num', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=10)),
                ('customer_id', models.CharField(max_length=12)),
                ('customer_pw', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=60)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_num', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField(max_length=500000)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product'),
        ),
    ]
